In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies_clean.csv")

df

,id,tmdb_id,imdb_id,title,adult,budget,genres,original_language,overview,popularity,production_companies,release_date,revenue,runtime,spoken_languages,status,vote_average,vote_count,count,collection_id
0,indiana+jones+and+the+last+crusade+1989,89.0,tt0097576,Indiana Jones and the Last Crusade,False,48000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",en,When Dr. Henry Jones Sr. suddenly goes missing...,14.788987,"[{'name': 'Lucasfilm', 'id': 1}, {'name': 'Par...",1989-05-24,474171806,127.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,7.6,3221,363419,84.0
1,brave+2012,62177.0,tt1217209,Brave,False,185000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",en,Brave is set in the mystical Scottish Highland...,15.876341,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...",2012-06-21,538983207,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,6.7,4760,182883,0.0
2,in+paris+2006,14654.0,tt0769508,In Paris,False,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",fr,"Paul, depressed from his recent break-up with ...",1.592146,"[{'name': 'Canal Plus', 'id': 104}, {'name': '...",2006-10-04,0,92.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,6.7,25,3394,0.0
3,out+of+bounds+2011,103972.0,tt1890445,Out of Bounds,False,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",da,"A desolate, windswept island. Stella and Oskar...",0.623994,"[{'name': 'Nordisk Film', 'id': 235}]",2011-05-13,0,73.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,5.0,1,2616,0.0
4,rosetta+1999,11489.0,tt0200071,Rosetta,False,0,"[{'id': 18, 'name': 'Drama'}]",fr,Young and impulsive Rosetta lives with her alc...,2.730118,"[{'name': 'ARP Sélection', 'id': 189}, {'name'...",1999-05-23,266665,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,7.2,52,6267,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26801,prom+night+iii+the+last+kiss+1990,41828.0,tt0098136,Prom Night III: The Last Kiss,False,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 35, 'n...",en,"Mary Lou, the prom queen burned to death by he...",1.506989,"[{'name': 'Norstar Entertainment', 'id': 16953...",1990-03-30,0,97.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,5.1,15,100,123255.0
26802,dirty+love+2005,18189.0,tt0327643,Dirty Love,False,0,"[{'id': 35, 'name': 'Comedy'}]",en,A modern day Cinderella story which sees disas...,7.125902,"[{'name': 'Big Screen Entertainment Group', 'i...",2005-09-23,0,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,4.9,26,94,0.0
26803,amityville+dollhouse+1996,52263.0,tt0115535,Amityville: Dollhouse,False,0,"[{'id': 27, 'name': 'Horror'}]",en,A dollhouse that is a replica of the infamous ...,2.357522,"[{'name': 'Zeta Entertainment', 'id': 5333}, {...",1996-10-02,0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,3.5,17,95,397842.0
26804,the+crew+2000,19150.0,tt0198386,The Crew,False,0,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",en,Four retired mobsters plan one last crime to s...,2.086952,"[{'name': 'Touchstone Pictures', 'id': 9195}]",2000-08-21,0,88.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,6.4,11,90,0.0
26805,turbo+a+power+rangers+movie+1997,6499.0,tt0120389,Turbo: A Power Rangers Movie,False,10000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",en,The legendary Power Rangers must stop the evil...,5.436745,[{'name': 'Twentieth Century Fox Film Corporat...,1997-03-27,17979739,99.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,4.6,60,1,286162.0

In [3]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [15]:
df[['budget', 'popularity', 'revenue', 'runtime', 'vote_count', 'vote_average']].head()

      budget  popularity    revenue  runtime  vote_count vote_average
0   48000000   14.788987  474171806    127.0        3221            3
1  185000000   15.876341  538983207     93.0        4760            3
2          0    1.592146          0     92.0          25            3
3          0    0.623994          0     73.0           1            2
4          0    2.730118     266665     95.0          52            3

In [4]:
# Convert the target variable to a categorical variable
df['vote_average'] = pd.cut(df['vote_average'], bins=[0.,2.,4.,6.,8.,10.], labels=[0,1,2,3,4])
df = df.dropna(subset=['vote_average'])
y = df['vote_average']
# Select the required features
X = df[['budget', 'popularity', 'revenue', 'runtime', 'vote_count']]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [14]:
X.head()

      budget  popularity    revenue  runtime  vote_count
0   48000000   14.788987  474171806    127.0        3221
1  185000000   15.876341  538983207     93.0        4760
2          0    1.592146          0     92.0          25
3          0    0.623994          0     73.0           1
4          0    2.730118     266665     95.0          52

In [5]:
import numpy as np
np.unique(y)

array([0, 1, 2, 3, 4])

In [6]:
# Create an instance of the XGBoost Classifier model
model = xgb.XGBClassifier()

# Fit the model to the training data
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              objective='multi:softprob', predictor=None, ...)

In [7]:
# Use the trained model to make predictions on the test set
y_pred = model.predict(X_test)

# Generate a classification report
report = classification_report(y_test, y_pred)

# Print the classification report
print(report)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        15
           1       0.36      0.02      0.03       228
           2       0.52      0.47      0.49      2027
           3       0.63      0.75      0.69      2777
           4       0.17      0.02      0.04        93

    accuracy                           0.59      5140
   macro avg       0.34      0.25      0.25      5140
weighted avg       0.57      0.59      0.57      5140

In [8]:
prediction = model.predict(X_test)

print('Predicted Ratings:', prediction)

Predicted Ratings: [2 2 3 ... 2 3 2]

In [9]:
y_pred = model.predict(X_test)

In [10]:
import eli5
from eli5 import explain_prediction

2023-04-04 19:13:30.317800: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [11]:
eli5.show_weights(model)

In [13]:
from eli5 import show_prediction
show_prediction(model, X_test.iloc[1], horizontal_layout=False, show_feature_values=True)